webtalk_init -webtalk_dir U:/LLRF/project_demuxes/project_demuxes.sim/sim_1/behav/xsim/xsim.dir/tb_Demuxes_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Jul 31 16:58:50 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2188600" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "210859171_177743539_210672202_462" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "87fcdf45-9999-4053-89cb-01a1447436f6" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "54651a2822ce485fbd9c0ee5483d63b3" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "104" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 7 , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Service Pack 1  (build 7601)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Xeon(R) CPU E5-1607 v2 @ 3.00GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2992 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "225 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.16_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "7976_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1760091166 -regid "210859171_177743539_210672202_462" -xml U:/LLRF/project_demuxes/project_demuxes.sim/sim_1/behav/xsim/xsim.dir/tb_Demuxes_behav/webtalk/usage_statistics_ext_xsim.xml -html U:/LLRF/project_demuxes/project_demuxes.sim/sim_1/behav/xsim/xsim.dir/tb_Demuxes_behav/webtalk/usage_statistics_ext_xsim.html -wdm U:/LLRF/project_demuxes/project_demuxes.sim/sim_1/behav/xsim/xsim.dir/tb_Demuxes_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
